# .github/workflows/ci.yml

# A more generic name for our pipeline
name: Continuous Integration

# We'll run this on pushes and pull requests to the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# The list of jobs to run
jobs:
  # A single job for testing the backend
  test-backend:
    name: Test Go Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'backend/go.mod'

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...