# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job 1: Test the Go backend
  test-backend:
    name: Test Go Backend
    runs-on: ubuntu-latest

    # NEW: Set a default working directory for all 'run' steps in this job.
    # This tells GitHub Actions to 'cd backend' before running any commands.
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Now that the context is the backend folder, the path is simpler.
          # The action will now correctly find go.mod and go.sum for caching.
          go-version-file: 'go.mod'

      - name: Build
        # The 'working-directory' key is no longer needed here because of the 'defaults' block above.
        run: go build -v ./...

      - name: Test
        # This step also inherits the default working directory.
        run: go test -v ./...