# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    name: Test Go Backend
    runs-on: ubuntu-latest

    # This is still good practice for our 'run' steps.
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # CORRECTED: The path must be relative to the repository root
          # because this 'uses:' step is not affected by the 'defaults.run' block.
          go-version-file: 'backend/go.mod'

      - name: Build
        # This step correctly uses the default working-directory
        run: go build -v ./...

      - name: Test
        # This step also correctly uses the default working-directory
        run: go test -v ./...